# Generated by Django 4.2.10 on 2025-07-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="end_date",
        ),
        migrations.AddField(
            model_name="batch",
            name="current_class",
            field=models.IntegerField(default=1),
        ),
    ]
