# Generated by Django 4.2.10 on 2025-07-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("academics", "0001_initial"),
        ("notebooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionrecord",
            name="associated_subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.subject",
            ),
        ),
        migrations.AlterField(
            model_name="submissionrecord",
            name="associated_teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.teacher",
            ),
        ),
    ]
