# Generated by Django 4.2.10 on 2025-08-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("notebooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionrecord",
            name="associated_batch",
            field=models.ForeignKey(
                default="batch_1",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.batch",
            ),
        ),
        migrations.AlterField(
            model_name="submissionrecord",
            name="associated_subject",
            field=models.ForeignKey(
                default="sub_1",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subject",
            ),
        ),
    ]
