# Generated by Django 4.2.10 on 2025-07-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("notebooks", "0002_alter_submissionrecord_associated_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionrecord",
            name="associated_subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subject",
            ),
        ),
    ]
