# Generated by Django 4.2.10 on 2025-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0002_alter_submissionrecord_associated_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionrecord",
            name="subject_context",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
