# Generated by Django 4.2.10 on 2025-07-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0004_submissionrecord_associated_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebooksubmission",
            name="submission_id",
            field=models.ForeignKey(
                default="sub_1",
                on_delete=django.db.models.deletion.CASCADE,
                to="notebooks.submissionrecord",
            ),
        ),
    ]
