# Generated by Django 4.2.10 on 2025-08-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0002_student_address_student_contact_number_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marksheet_id", models.CharField(max_length=50)),
                ("forclass", models.IntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.batch"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="scorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.IntegerField()),
                ("hindi_theory", models.IntegerField()),
                ("hindi_assessment", models.IntegerField()),
                ("english_theory", models.IntegerField()),
                ("english_assessment", models.IntegerField()),
                ("maths_theory", models.IntegerField()),
                ("maths_assessment", models.IntegerField()),
                ("science_theory", models.IntegerField()),
                ("science_assessment", models.IntegerField()),
                ("sst_evs_theory", models.IntegerField()),
                ("sst_evs_assessment", models.IntegerField()),
                ("drawing_theory", models.IntegerField()),
                ("drawing_assessment", models.IntegerField()),
                ("computer_music_theory", models.IntegerField()),
                ("computer_music_assessment", models.IntegerField()),
                ("gk_theory", models.IntegerField()),
                ("gk_assessment", models.IntegerField()),
                ("punjabi_skt_theory", models.IntegerField()),
                ("punjabi_skt_assessment", models.IntegerField()),
                (
                    "marksheet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marksheet.marksheet",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.student"
                    ),
                ),
            ],
        ),
    ]
