# Generated by Django 4.2.10 on 2025-08-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marksheet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marksheet",
            name="teacher",
        ),
    ]
