# Generated by Django 4.2.10 on 2025-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marksheet", "0002_remove_marksheet_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scorecard",
            name="term",
        ),
        migrations.AddField(
            model_name="marksheet",
            name="term",
            field=models.IntegerField(default=1),
        ),
    ]
