# Generated by Django 4.2.10 on 2025-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marksheet", "0003_remove_scorecard_term_marksheet_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marksheet",
            name="term",
            field=models.CharField(default="2025-26_1", max_length=10),
        ),
    ]
