# Generated by Django 4.2.10 on 2025-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marksheet", "0004_alter_marksheet_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorecard",
            name="drawing_assessment",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="drawing_theory",
            field=models.CharField(default="", max_length=1),
        ),
    ]
