# Generated by Django 4.2.10 on 2025-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marksheet", "0005_alter_scorecard_drawing_assessment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorecard",
            name="computer_music_assessment",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="computer_music_theory",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="gk_assessment",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="gk_theory",
            field=models.CharField(default="", max_length=1),
        ),
    ]
