# Generated by Django 4.2.10 on 2025-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marksheet", "0006_alter_scorecard_computer_music_assessment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorecard",
            name="computer_music_assessment",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="computer_music_theory",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="drawing_assessment",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="drawing_theory",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="gk_assessment",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="gk_theory",
            field=models.IntegerField(default=0),
        ),
    ]
