# Generated by Django 4.2.10 on 2025-08-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_student_address_student_contact_number_and_more"),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=20, unique=True)),
                ("session", models.CharField(max_length=7)),
                ("report_class", models.IntegerField()),
                (
                    "teacher_incharge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_teacher",
                        to="people.teacher",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
        migrations.AddField(
            model_name="reportcard",
            name="report_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.resultreport"
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people.student"
            ),
        ),
    ]
