# Generated by Django 4.2.10 on 2025-07-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="classroom",
        ),
    ]
