# Generated by Django 4.2.10 on 2025-07-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0003_alter_submissionrecord_associated_subject"),
        ("academics", "0002_remove_subject_classroom"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
